print("Selamat Datang di Toko 71")
print("Masukkan Nama Barang yang Ingin Dibeli ")
NamaBarang = (input())
print("Masukkan Jumlah Barang Anda ")
JumlahBarang = int(input())
print("Masukkan Harga Satuan Barang ")
HargaBarang = float(input())
print("Selamat Anda Mendapatkan DISKON 71% !!!")
TotalHargaAwal = JumlahBarang * HargaBarang
print("Harga Awal Barang Anda adalah ")
print(TotalHargaAwal)
print(" Ketik apapun untuk melihat Total Diskon yang Anda Dapat ")
DISKON = input()
TotalDiskon = 0.71 * TotalHargaAwal
print("Total DISKON yang Anda Dapatkan Adalah ")
print(TotalDiskon)
print(" Ketik apapun untuk melihat Total Pembelian Anda ")
JUMLAH = input()
totalHargaAkhir = TotalHargaAwal - TotalDiskon
print("Total Harga Barang Belanjaan Anda Adalah ")
print(totalHargaAkhir) 
print(f"Anda membeli {JumlahBarang} {NamaBarang}")
print(f" dengan harga satuan {HargaBarang}" )
print(f" total harga sebelum diskon adalah {TotalHargaAwal}") 
print(f" total diskon yang Anda dapatkan adalah {TotalDiskon}" )
print(f" dan total harga yang harus dibayar adalah {totalHargaAkhir}")
print("Sisa Pembagian Diskon 71 Dengan 3 adalah 2")